### ISSUE TITLE
[Request] Server Uptime

### ISSUE THREAD

**Issue by DJBoxer** [ShinDarth/TC-Server-Status#3]
Would it be possible to add server uptime or explain how i would go about adding it as im unsure where to look.

Kind regards,

**Comment by FrancescoBorzi** [comment]
you need to extract this information from the API

**Comment by DJBoxer** [comment]
How to i go about extracting it then? please can you explain more.

**Comment by FrancescoBorzi** [comment]
This application requests data from the TC API ( https://github.com/ShinDarth/TC-JSON-API ). Unfortunately I do not develop the API anymore, but feel free to browse the project. Sorry that I can't help you further

**Comment by DJBoxer** [comment]
yeah ok, sorry to be annoying lol.
I believe i`ve found sort of rough idea with auth routes.

Route: /uptime
Optional multiple parameters: realmid, time.
Using realmid parameter to choose which realm uptime to get.
Using time to get the string "uptime" converted into Day, Hours and Mins.

As i believe this TC-server-status is im gussing using /pulse.

Wondering if i can just add it in guess one way to find out lol.

**Comment by FrancescoBorzi** [comment]
@DJBoxer that project was my first experiment when trying to approach to this kind of stuff. So it can definitely be made better. Feel free to play with it and I wish you all success.
