### ISSUE TITLE
Putting it into a PHP include in another directory

### ISSUE THREAD

**Issue by GnaXi** [ShinDarth/TC-Server-Status#4]
It really dislikes to be put into a PHP include in another directory:
![image](https://user-images.githubusercontent.com/1616448/28121105-5c3e0e9c-671a-11e7-83fc-5a3f6975d53a.png)

Format and link to the API is lost entirely.

**Comment by FrancescoBorzi** [comment]
the API should run independently and be accessible via http calls, so it's not about php include

**Comment by GnaXi** [comment]
It works just fine outside of the php include, so I wouldn't rush to a conclusion :P 
As you can see it works just fine here:
https://gnax.io/wow/status3/index.html

But when I put this into a PHP include here:
https://gnax.io/world-of-warcraft/
I get what i previously posted here.

**Comment by FrancescoBorzi** [comment]
``app.api="../tc-json-api/public/index.php"``

the path can't be relative because they are communicating at HTTP leve, so you should put the public accessible path, for example:

``http://keira2.altervista.org/TC-JSON-API/public/index.php``

**Comment by GnaXi** [comment]
I just changed it to https://gnax.io/wow/tc-json-api/public/index.php
Unfortunately the issue remains the same.

**Comment by FrancescoBorzi** [comment]
@GnaXi if you use the Chrome Dev Tools you will see in the Network page that the javascript files aren't correctly loaded:

![image](https://user-images.githubusercontent.com/75517/28133895-9ee1a9a8-6741-11e7-8a28-4d0107f3bbf1.png)

which is not related with the API

**Comment by GnaXi** [comment]
Which is why I put the issue in the TC-Server-Status rep and not in the TC-JSON-API rep?

**Comment by GnaXi** [comment]
I figured it out.
Going to the index.html file for Server-Status and changing the link for all of the javascripts to the full HTTP address resolved the issue :)
